const items = [
  {name:"Compteur d'eau",cat:"Alimentation",icon:"◉",short:"Mesure le volume d'eau consommé par une installation.",role:"Installé en limite de propriété ou en gaine technique, il comptabilise les m³. La flèche gravée indique le sens de circulation.",install:"Accessible, cadran lisible, après le robinet d'arrêt général. Respecter le sens de pose et les prescriptions du distributeur.",check:"Rechercher fuite, gel, plombage et index anormal. Ne jamais intervenir sur un compteur plombé.",plan:"CPT ou symbole circulaire sur la conduite EF."},
  {name:"Robinet d'arrêt",cat:"Alimentation",icon:"✣",short:"Isole tout ou partie d'un réseau pour intervenir.",role:"Coupe rapidement l'alimentation générale ou locale. Modèles à boisseau sphérique recommandés pour une faible perte de charge.",install:"Avant chaque équipement sensible et sur les départs. Poignée accessible, diamètre adapté, sens si indiqué.",check:"Manœuvrer périodiquement, contrôler presse-étoupe et étanchéité.",plan:"RA, vanne ou deux triangles pointe contre pointe."},
  {name:"Robinet de vidange",cat:"Alimentation",icon:"♧",short:"Permet de vider une canalisation ou une installation.",role:"Évacue l'eau au point bas pour maintenance, hivernage ou réparation.",install:"Toujours au point bas, avec raccord permettant de brancher un tuyau. Prévoir une évacuation sûre.",check:"Fermer sans forcer après usage et vérifier l'absence de goutte-à-goutte.",plan:"RV au point bas, souvent associé à une vanne."},
  {name:"Réducteur de pression",cat:"Sécurité",icon:"↘",short:"Stabilise la pression en aval du réseau public.",role:"Ramène généralement une pression trop forte vers environ 3 bar pour protéger appareils, robinetterie et limiter le bruit.",install:"Après compteur et clapet, flèche dans le sens de l'eau. Prévoir manomètre et accès au réglage.",check:"Mesurer pression statique/dynamique. Nettoyer le filtre et remplacer la cartouche si dérive.",plan:"RP avec pression de consigne indiquée."},
  {name:"Groupe de sécurité",cat:"Sécurité",icon:"◒",short:"Protège le chauffe-eau contre la surpression.",role:"Réunit robinet d'arrêt, clapet antiretour, soupape tarée à 7 bar et vidange. Un écoulement pendant la chauffe est normal.",install:"Directement sur l'entrée EF du ballon, sans vanne entre groupe et ballon. Évacuation par siphon avec garde d'air.",check:"Actionner la soupape mensuellement. Détartrer ou remplacer s'il fuit hors chauffe.",plan:"GS à l'entrée EF du chauffe-eau."},
  {name:"Clapet antiretour",cat:"Sécurité",icon:"▷|",short:"Empêche l'eau de repartir en sens inverse.",role:"Évite les retours d'eau susceptibles de polluer le réseau et les inversions de circulation.",install:"Respecter impérativement la flèche, rester accessible, choisir la classe de protection adaptée.",check:"Contrôler fermeture et pertes de charge; nettoyer si bloqué.",plan:"Triangle ou flèche face à une barre."},
  {name:"Disconnecteur",cat:"Sécurité",icon:"◁◇▷",short:"Protège le réseau potable contre les retours polluants.",role:"Sépare deux réseaux par une zone de pression réduite contrôlable, notamment pour le remplissage chauffage.",install:"Horizontal selon modèle, accessible, avec évacuation visible et robinets de contrôle.",check:"Contrôle réglementaire selon installation; surveiller toute décharge anormale.",plan:"CA/BA selon le type et le niveau de risque."},
  {name:"Siphon",cat:"Évacuation",icon:"∪",short:"Bloque les remontées d'odeurs grâce à sa garde d'eau.",role:"Crée une barrière hydraulique entre appareil et réseau d'eaux usées.",install:"Sous chaque appareil, démontable et accessible. Respecter diamètre et garde d'eau, sans contre-pente.",check:"Nettoyer le culot et vérifier joints; remettre de l'eau après longue absence.",plan:"Siphon stylisé sous lavabo, évier ou appareil."},
  {name:"Bonde",cat:"Évacuation",icon:"⊙",short:"Relie la cuve de l'appareil sanitaire au siphon.",role:"Assure l'écoulement et parfois la fermeture du lavabo, évier, douche ou baignoire.",install:"Joint côté appareil selon fabricant, serrage modéré, mastic seulement si prescrit. Avec ou sans trop-plein.",check:"Tester l'étanchéité cuve pleine puis en vidange.",plan:"Au point d'évacuation de l'appareil."},
  {name:"Vidage de baignoire",cat:"Évacuation",icon:"⌣",short:"Ensemble bonde, trop-plein et commande de fermeture.",role:"Évacue la baignoire et empêche son débordement via le trop-plein.",install:"Accessible par trappe, câble sans coude serré, joints parfaitement placés.",check:"Essai cuve pleine, contrôle du trop-plein et de la commande.",plan:"VB / évacuation Ø40 généralement."},
  {name:"Manchon",cat:"Évacuation",icon:"▭",short:"Assemble deux tubes de même diamètre.",role:"Raccord droit femelle-femelle, à coller pour PVC ou à sertir/visser selon matériau.",install:"Coupe d'équerre, ébavurage, emboîture propre; respecter profondeur et temps de prise.",check:"Vérifier alignement et étanchéité avant encastrement.",plan:"Trait de jonction sur canalisation, diamètre noté Ø."},
  {name:"Culotte PVC",cat:"Évacuation",icon:"Y",short:"Raccorde une évacuation secondaire au collecteur.",role:"Sa forme oblique guide les effluents et limite turbulences et bouchons.",install:"Orienter dans le sens d'écoulement. Préférer 45°; respecter pente de 1 à 3 cm/m selon réseau.",check:"Pas de contrainte ni contre-pente; tampon de visite si nécessaire.",plan:"Jonction en Y avec diamètres principal/branche."},
  {name:"Tampon de visite",cat:"Évacuation",icon:"⊣",short:"Donne accès au réseau pour débouchage et inspection.",role:"Permet passage d'un furet ou d'une caméra sans démonter l'installation.",install:"Aux changements de direction et pieds de chute, toujours accessible.",check:"Joint propre, bouchon serré sans excès, absence de fuite.",plan:"TV ou bouchon à l'extrémité d'une dérivation."},
  {name:"Aérateur à membrane",cat:"Évacuation",icon:"⇡",short:"Admet de l'air et limite le désiphonnage.",role:"Compense ponctuellement la dépression dans les évacuations sans remplacer systématiquement la ventilation primaire.",install:"Vertical, au-dessus du niveau de débordement, ventilé et accessible.",check:"Remplacer si odeurs ou membrane collée.",plan:"AAV / aérateur en tête de branche."},
  {name:"Mitigeur",cat:"Robinetterie",icon:"♜",short:"Règle débit et température avec une seule commande.",role:"Mélange EC et EF via une cartouche céramique. Peut intégrer limiteur de débit et température.",install:"EC à gauche, EF à droite. Purger avant raccordement et poser filtres/joints fournis.",check:"Détartrer mousseur; cartouche à contrôler si débit faible ou fuite.",plan:"M ou symbole robinet aux points de puisage."},
  {name:"Mélangeur",cat:"Robinetterie",icon:"♆",short:"Deux commandes séparées pour eau chaude et froide.",role:"Le mélange est réalisé dans le corps après réglage des deux têtes.",install:"EC à gauche, EF à droite, entraxe conforme. Ne pas sur-serrer les raccords.",check:"Changer clapet ou tête en cas de goutte-à-goutte.",plan:"Robinet à deux commandes."},
  {name:"Mitigeur thermostatique",cat:"Robinetterie",icon:"◐",short:"Maintient automatiquement la température choisie.",role:"Compense les variations de pression et possède souvent une butée de sécurité à 38 °C.",install:"Arrivées dans le bon sens, filtres propres, équilibrage des pressions recommandé.",check:"Étalonner la température et détartrer la cartouche thermostatique.",plan:"MT sur douche/baignoire."},
  {name:"Mécanisme de chasse",cat:"Robinetterie",icon:"⇊",short:"Libère puis renouvelle l'eau du réservoir WC.",role:"Associe robinet flotteur et soupape simple ou double volume pour limiter la consommation.",install:"Régler niveau sous trop-plein, centrer le joint de cuve et adapter la commande.",check:"Colorant dans la cuvette pour détecter une fuite silencieuse.",plan:"À l'intérieur du réservoir WC."},
  {name:"Robinet flotteur",cat:"Robinetterie",icon:"◯",short:"Remplit un réservoir et ferme au niveau réglé.",role:"Utilisé principalement dans les réservoirs WC; ouverture commandée par la position du flotteur.",install:"Latéral ou bas, joint intérieur conforme à la notice; réglage sans contact avec les parois.",check:"Nettoyer filtre et membrane si remplissage lent ou continu.",plan:"RF dans le réservoir."},
  {name:"Flexible sanitaire",cat:"Alimentation",icon:"〰",short:"Assure une liaison souple entre réseau et appareil.",role:"Absorbe les petits écarts d'alignement pour robinets, WC et appareils.",install:"Sans torsion, traction ni coude trop serré. Longueur adaptée et date/usage compatibles.",check:"Remplacer si corrosion, hernie ou tresse abîmée; ne pas encastrer sauf modèle autorisé.",plan:"Trait souple en dernier raccordement."},
  {name:"Collecteur nourrice",cat:"Alimentation",icon:"≡",short:"Distribue un départ individuel vers chaque appareil.",role:"Centralise la distribution en pieuvre, facilite l'équilibrage et l'isolement.",install:"Dans un endroit accessible, repérer chaque départ, prévoir vannes et diamètres calculés.",check:"Contrôler raccords et étiquetage; laisser les sorties inutilisées bouchonnées.",plan:"Barre avec plusieurs départs EF/EC."},
  {name:"Vase d'expansion sanitaire",cat:"Sécurité",icon:"⬭",short:"Absorbe la dilatation de l'eau chaude sanitaire.",role:"Réduit les écoulements du groupe de sécurité et les variations de pression lors de la chauffe.",install:"Entre groupe et ballon suivant prescriptions, vessie compatible ECS, pression de gonflage réglée.",check:"Contrôler gonflage hors pression et état de la membrane.",plan:"VES près du ballon ECS."},
  {name:"Anti-bélier",cat:"Sécurité",icon:"⚡",short:"Amortit les coups de bélier à la fermeture rapide.",role:"Une chambre ou membrane absorbe l'onde de pression qui fait vibrer les canalisations.",install:"Au plus près de l'organe générateur, dans la position prescrite.",check:"Vérifier fixation des tubes et pression avant de conclure à son remplacement.",plan:"AB près d'une électrovanne ou robinet rapide."},
  {name:"Manomètre",cat:"Alimentation",icon:"◴",short:"Affiche la pression du réseau en bar.",role:"Permet diagnostic et réglage d'un réducteur, groupe de remplissage ou réseau.",install:"Plage de mesure adaptée, lisible, avec vanne d'isolement si nécessaire.",check:"Comparer à une référence; aiguille à zéro hors pression.",plan:"Cercle avec aiguille, repère P ou MAN."}
];

const questions = [
  ["À quoi sert principalement un groupe de sécurité ?",["Protéger le ballon contre la surpression","Augmenter le débit d'eau chaude","Filtrer le calcaire","Mesurer la consommation"],0,"Sa soupape tarée évacue la dilatation pendant la chauffe.","Sécurité"],
  ["Où installe-t-on un robinet de vidange ?",["Au point bas de l'installation","Au point le plus haut","Après chaque siphon","Sur la ventilation primaire"],0,"L'eau doit pouvoir s'écouler naturellement lors de la vidange.","Alimentation"],
  ["Sur un plan, que signifie généralement EF ?",["Eau froide","Évacuation finale","Entrée filtrée","Étage fini"],0,"EF désigne l'alimentation en eau froide.","Lecture de plan"],
  ["Quelle pente est couramment recherchée pour une évacuation horizontale ?",["Environ 1 à 3 cm par mètre","10 cm par mètre","Aucune pente","Toujours 20 %"],0,"Une pente régulière de 1 à 3 cm/m favorise l'auto-curage selon diamètre et règles applicables.","Évacuation"],
  ["Quel accessoire empêche les remontées d'odeurs ?",["Le siphon","Le manomètre","Le collecteur","Le réducteur"],0,"La garde d'eau du siphon forme une barrière aux gaz.","Évacuation"],
  ["Sur un mitigeur, l'eau chaude est normalement raccordée…",["À gauche","À droite","Au centre","Indifféremment"],0,"La convention courante place EC à gauche et EF à droite.","Robinetterie"],
  ["Une flèche gravée sur un clapet indique…",["Le sens d'écoulement","La pression maximale","Le diamètre nominal","Le sens de démontage"],0,"Un clapet posé à l'envers bloque ou perturbe l'installation.","Sécurité"],
  ["Que signifie Ø40 sur un plan ?",["Un diamètre de 40 mm","Une pente de 40 %","Une longueur de 40 cm","Une pression de 40 bar"],0,"Le symbole Ø précède le diamètre de la canalisation.","Lecture de plan"],
  ["Pourquoi poser un réducteur de pression ?",["Protéger l'installation d'une pression excessive","Chauffer l'eau plus vite","Ventiler une chute","Évacuer les condensats"],0,"Il stabilise une pression aval compatible avec les appareils.","Sécurité"],
  ["Quel test simple détecte une fuite de chasse WC ?",["Mettre un colorant dans le réservoir","Augmenter la pression","Fermer le siphon","Chauffer la cuvette"],0,"Le colorant apparaît dans la cuvette si la soupape n'est plus étanche.","Robinetterie"],
  ["À quoi sert le tampon de visite ?",["Accéder au réseau pour le curage","Régler la température","Couper l'eau générale","Mesurer le débit"],0,"Il permet d'introduire un furet ou une caméra.","Évacuation"],
  ["Une canalisation rouge sur un plan sanitaire représente souvent…",["L'eau chaude","L'eau froide","Les eaux vannes","Le gaz sans exception"],0,"La convention rouge/bleu est fréquente, mais la légende du plan reste prioritaire.","Lecture de plan"],
  ["Que doit-on faire avant de raccorder une robinetterie neuve ?",["Purger/rincer les canalisations","Graisser tous les joints","Supprimer les filtres","Fermer l'évacuation"],0,"Le rinçage évite que des débris endommagent cartouches et mousseurs.","Robinetterie"],
  ["Quel raccord favorise l'écoulement d'une dérivation EU ?",["Une culotte orientée dans le sens du flux","Un té à angle vif à contre-sens","Un clapet EF","Un flexible tordu"],0,"La branche oblique limite les turbulences et dépôts.","Évacuation"],
  ["À quoi sert un disconnecteur sur le remplissage chauffage ?",["Éviter un retour d'eau polluée vers l'eau potable","Faire circuler l'eau chaude","Augmenter la pression publique","Remplacer le circulateur"],0,"Il protège le réseau potable contre la contamination par retour.","Sécurité"],
  ["Que signifie ECS ?",["Eau chaude sanitaire","Écoulement contrôlé secondaire","Entrée de canalisation sécurisée","Eau chargée standard"],0,"ECS désigne l'eau chaude destinée aux usages sanitaires.","Lecture de plan"],
  ["Quelle est la fonction d'une nourrice ?",["Distribuer des départs individuels","Retenir les odeurs","Produire l'eau chaude","Évacuer une baignoire"],0,"Le collecteur centralise et identifie les circuits.","Alimentation"],
  ["Un flexible sanitaire doit être posé…",["Sans torsion ni traction","Tendu au maximum","Avec un nœud anti-fuite","Directement noyé dans le béton"],0,"Une pose libre et un rayon correct préservent sa durée de vie.","Alimentation"],
  ["Pourquoi ventiler un réseau d'évacuation ?",["Équilibrer les pressions et préserver les siphons","Refroidir l'eau potable","Augmenter la pente","Réduire le diamètre"],0,"L'entrée d'air évite les dépressions responsables du désiphonnage.","Évacuation"],
  ["Que mesure un manomètre ?",["La pression","Le débit cumulé","La température uniquement","La pente"],0,"La pression est généralement lue en bar sur les installations sanitaires.","Alimentation"]
];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let category="Tous", expanded=false;
const filters=["Tous","Alimentation","Évacuation","Robinetterie","Sécurité"];

// Symboles schématiques usuels de plomberie. La légende du plan du chantier reste
// toujours prioritaire : les bureaux d'études peuvent employer des variantes.
function symbolSVG(name){
  const common=(inside,extra="")=>`<svg class="trade-symbol" viewBox="0 0 120 86" role="img" aria-label="Symbole de ${name}"><path class="pipe" d="M4 43h28M88 43h28"/>${inside}${extra}</svg>`;
  const symbols={
    "Compteur d'eau":`<circle class="main" cx="60" cy="43" r="25"/><text x="52" y="47">CPT</text>`,
    "Robinet d'arrêt":`<path class="main" d="M32 27 60 43 32 59Zm56 0L60 43l28 16Z"/><path class="detail" d="M60 43V17h17"/>`,
    "Robinet de vidange":`<path class="main" d="M32 27 60 43 32 59Zm56 0L60 43l28 16Z"/><path class="detail" d="M60 43v27m-8 0h16"/>`,
    "Réducteur de pression":`<path class="main" d="M34 25 60 43 34 61Zm52 7L60 43l26 11Z"/><path class="detail" d="M60 43V16m-11 0h22"/>`,
    "Groupe de sécurité":`<rect class="main" x="34" y="21" width="52" height="44"/><path class="detail" d="M42 43h36M49 34l11 9-11 9m22-18v18M60 65v15m-7-5h14"/>`,
    "Clapet antiretour":`<path class="main" d="m34 25 34 18-34 18Z"/><path class="main" d="M72 24v38"/>`,
    "Disconnecteur":`<path class="main" d="m28 27 25 16-25 16Zm64 0L67 43l25 16Z"/><path class="detail" d="M60 31v39m-9 0h18"/>`,
    "Siphon":`<path class="main" d="M30 20v30c0 30 60 30 60 0V20"/><path class="detail" d="M31 54c17 8 41 8 58 0"/>`,
    "Bonde":`<circle class="main" cx="60" cy="43" r="21"/><circle class="detail" cx="60" cy="43" r="8"/><path class="detail" d="M47 30l26 26m0-26L47 56"/>`,
    "Vidage de baignoire":`<path class="main" d="M20 29v20c0 14 12 23 27 23h39c13 0 20-9 20-23"/><circle class="detail" cx="91" cy="37" r="6"/><path class="detail" d="M91 43v20M55 72v9"/>`,
    "Manchon":`<rect class="main" x="35" y="29" width="50" height="28"/><path class="detail" d="M45 29v28m30-28v28"/>`,
    "Culotte PVC":`<path class="main" d="M17 64h47V20M58 48l33-27"/><path class="detail" d="m83 20 9 1-2 9"/>`,
    "Tampon de visite":`<path class="main" d="M20 43h60M80 24v38"/><rect class="detail" x="83" y="29" width="15" height="28"/>`,
    "Aérateur à membrane":`<path class="main" d="M60 72V38M42 38h36V20H42Z"/><path class="detail" d="M48 29h24M60 15V5m-9 8 9-8 9 8"/>`,
    "Mitigeur":`<circle class="main" cx="60" cy="43" r="23"/><path class="detail" d="M45 50h30M60 50V27m-13 0h26"/><text x="56" y="63">M</text>`,
    "Mélangeur":`<circle class="main" cx="60" cy="43" r="23"/><path class="detail" d="M43 31h34M48 24v14m24-14v14M60 43v19"/>`,
    "Mitigeur thermostatique":`<circle class="main" cx="60" cy="43" r="25"/><text x="52" y="47">MT</text><path class="detail" d="M60 18v-8"/>`,
    "Mécanisme de chasse":`<rect class="main" x="34" y="14" width="52" height="58"/><path class="detail" d="M60 22v34m-9-10 9 10 9-10M45 66h30"/>`,
    "Robinet flotteur":`<path class="main" d="M25 43h42m0-18v36"/><path class="detail" d="M67 34h17l12 19"/><circle class="main" cx="98" cy="58" r="8"/>`,
    "Flexible sanitaire":`<path class="main" d="M12 53c18-43 35 34 53-9s28 22 43-10"/><path class="detail" d="M11 44v18m97-37v18"/>`,
    "Collecteur nourrice":`<path class="main" d="M19 43h82M38 43v29m22-29v29m22-29v29"/><path class="detail" d="M31 63h14m8 0h14m8 0h14"/>`,
    "Vase d'expansion sanitaire":`<ellipse class="main" cx="60" cy="43" rx="27" ry="34"/><path class="detail" d="M34 43h52M60 77v7"/><text x="52" y="36">VES</text>`,
    "Anti-bélier":`<path class="main" d="M60 72V34h27V10H60v24"/><path class="detail" d="m46 19 13-12-4 13 12-2-17 18 5-15Z"/>`,
    "Manomètre":`<circle class="main" cx="60" cy="39" r="28"/><path class="detail" d="M60 39 75 24M60 67v15"/><text x="36" y="45">bar</text>`
  };
  return common(symbols[name]||`<circle class="main" cx="60" cy="43" r="24"/><text x="56" y="47">?</text>`);
}

function renderFilters(){ $("#filters").innerHTML=filters.map(f=>`<button class="filter ${f===category?'active':''}" data-filter="${f}">${f}</button>`).join(""); $$(".filter").forEach(b=>b.onclick=()=>{category=b.dataset.filter;expanded=false;renderFilters();renderCards()}) }
function renderCards(){ const q=$("#search").value.toLowerCase().trim(); let shown=items.filter(i=>(category==="Tous"||i.cat===category)&&(`${i.name} ${i.short} ${i.role}`).toLowerCase().includes(q)); const limited=expanded?shown:shown.slice(0,8); $("#catalogue-grid").innerHTML=limited.map((i,n)=>`<button class="item-card" data-name="${i.name}"><span class="num">${String(n+1).padStart(2,'0')} — ${i.cat.toUpperCase()}</span><span class="icon">${symbolSVG(i.name)}</span><span class="tag">SYMBOLE SCHÉMATIQUE · FICHE</span><h3>${i.name}</h3><p>${i.short}</p><span class="arrow">↗</span></button>`).join(""); $("#empty-state").hidden=shown.length>0; $("#show-more").hidden=shown.length<=8; $("#show-more").innerHTML=expanded?'Réduire la liste <span>↑</span>':'Afficher toutes les fiches <span>↓</span>'; $$(".item-card").forEach(c=>c.onclick=()=>openDetail(items.find(i=>i.name===c.dataset.name))) }
function openDetail(i){ $("#modal-content").innerHTML=`<div class="modal-body"><span class="kicker">${i.cat.toUpperCase()} · FICHE MÉTIER</span><div class="modal-icon">${symbolSVG(i.name)}</div><h2>${i.name}</h2><p>${i.short}</p><div class="detail-grid"><div class="detail-box"><b>RÔLE</b><p>${i.role}</p></div><div class="detail-box"><b>POSE</b><p>${i.install}</p></div><div class="detail-box"><b>CONTRÔLE</b><p>${i.check}</p></div><div class="detail-box"><b>SUR LE PLAN</b><p>${i.plan}</p></div></div><p class="symbol-note">Symbole schématique usuel. Toujours vérifier la légende : sa représentation peut varier selon le bureau d'études et le type de plan.</p></div>`; $("#detail-modal").showModal() }
$("#search").oninput=renderCards; $("#show-more").onclick=()=>{expanded=!expanded;renderCards()};

const legends=[["EF","Eau froide","Souvent tracée en bleu, avec son diamètre."],["EC","Eau chaude","Souvent tracée en rouge; ECS = eau chaude sanitaire."],["EU","Eaux usées","Lavabo, douche, évier : pente et diamètre sont essentiels."],["EV","Eaux-vannes","Eaux des WC, souvent en Ø100 selon le réseau."],["EP","Eaux pluviales","Réseau séparé des eaux usées selon le système."]];
$("#legend-list").innerHTML=legends.map(l=>`<div class="legend-row"><span class="symbol">${l[0]}</span><div><b>${l[1]}</b><span>${l[2]}</span></div></div>`).join("");
const guide=["Commencer par le cartouche : niveau, échelle, indice et date.","Lire la légende : les couleurs et symboles peuvent varier d'un bureau d'études à l'autre.","Repérer l'arrivée générale, le compteur, la vanne et les colonnes.","Suivre EF puis EC jusqu'à chaque appareil; relever matériau et diamètre.","Suivre EU/EV dans le sens des flèches; contrôler diamètre, pente et ventilation.","Comparer plans architecte, plomberie et coupes pour détecter les conflits.","Reporter niveaux et cotes depuis une référence fiable, jamais depuis une impression non vérifiée.","Avant travaux, vérifier sur site : un plan ne remplace pas la reconnaissance du chantier."];
$("#plan-guide-content").innerHTML=`<div class="guide-steps">${guide.map((g,i)=>`<div class="guide-step"><b>${i+1}. Étape</b><span>${g}</span></div>`).join('')}</div>`;
$("#open-plan-guide").onclick=()=>$("#plan-modal").showModal(); $$(".modal-close").forEach(b=>b.onclick=()=>b.closest("dialog").close()); $$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});

const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const clean=s=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");
const aliases={"compteur d'eau":["compteur","compteur eau"],"robinet d'arrêt":["vanne d'arret","vanne"],"robinet de vidange":["vanne de vidange"],"clapet antiretour":["clapet anti retour"],"collecteur nourrice":["nourrice","collecteur"],"vase d'expansion sanitaire":["vase expansion","ves"],"mitigeur thermostatique":["thermostatique"],"aérateur à membrane":["aerateur","aav"]};
const legacyQuestions=questions.map(q=>({prompt:q[0],choices:q[1],correct:q[2],explanation:q[3],category:q[4],type:"qcm"}));
function distractors(item){return shuffle(items.filter(i=>i.name!==item.name&&i.cat===item.cat)).slice(0,3).map(i=>i.name)}
const generatedQuestions=items.flatMap(item=>[
  {prompt:`Quel accessoire correspond à cette définition : « ${item.short} » ?`,choices:shuffle([item.name,...distractors(item)]),answer:item.name,explanation:item.role,category:item.cat,type:"qcm-name"},
  {prompt:`Écrivez le nom de l'accessoire : ${item.short}`,answer:item.name,explanation:item.role,category:item.cat,type:"written"},
  {prompt:"Reconnaissez ce symbole et écrivez le nom complet de l'accessoire.",answer:item.name,explanation:`Sur un plan : ${item.plan}`,category:item.cat,type:"symbol",symbol:item.name},
  {prompt:`Quel accessoire est concerné par cette règle de pose : « ${item.install} » ?`,answer:item.name,explanation:`Il s'agit du ${item.name}. ${item.check}`,category:item.cat,type:"written"}
]);
const planWritten=[
  ["Que signifie l'abréviation EF ?","eau froide","EF repère l'alimentation en eau froide."],
  ["Que signifie l'abréviation EC ?","eau chaude","EC repère l'alimentation en eau chaude."],
  ["Que signifie l'abréviation ECS ?","eau chaude sanitaire","ECS désigne l'eau chaude destinée aux usages sanitaires."],
  ["Que signifie l'abréviation EU ?","eaux usées","EU désigne généralement les eaux de lavabo, douche ou évier."],
  ["Que signifie l'abréviation EV ?","eaux vannes","EV désigne les eaux provenant des WC."],
  ["Que signifie l'abréviation EP ?","eaux pluviales","EP désigne les eaux de pluie."],
  ["Écrivez en millimètres le diamètre indiqué par Ø40.","40","Le symbole Ø précède le diamètre nominal en millimètres."],
  ["Une pente notée 2 % représente combien de centimètres par mètre ?","2","2 % correspond à 2 cm de dénivelé par mètre."],
  ["Quel document du plan définit en priorité la signification des traits et symboles ?","legende","La légende propre au projet est toujours prioritaire."],
  ["Comment appelle-t-on le cadre qui indique titre, échelle, date et indice du plan ?","cartouche","Le cartouche identifie et versionne le document."]
].map(q=>({prompt:q[0],answer:q[1],explanation:q[2],category:"Lecture de plan",type:"written",accepted:[q[1]]}));
const questionBank=[...legacyQuestions,...generatedQuestions,...planWritten];
let game=[], current=0, score=0, answered=false;
function updateBest(){const best=localStorage.getItem('plomberieBest');$("#best-score").textContent=`Votre meilleur score : ${best?best+' bonne(s) réponse(s)':'—'}`}
function startQuiz(){let pool=[...questionBank],cat=$("#quiz-category").value,mode=$("#quiz-mode").value;if(cat!=="Tous")pool=pool.filter(q=>q.category===cat);if(mode==="qcm")pool=pool.filter(q=>q.type.startsWith("qcm"));if(mode==="ecrit")pool=pool.filter(q=>q.type==="written");if(mode==="symboles")pool=pool.filter(q=>q.type==="symbol");const wanted=$("#quiz-length").value;let length=wanted==="all"?pool.length:Number(wanted);game=shuffle(pool).slice(0,Math.min(length,pool.length));current=score=0;$("#quiz-placeholder").hidden=true;$("#quiz-results").hidden=true;$("#quiz-game").hidden=false;showQuestion()}
function showQuestion(){answered=false;const q=game[current];$("#quiz-progress").textContent=`QUESTION ${current+1} / ${game.length}`;$("#quiz-score").textContent=`${score} POINT${score>1?'S':''}`;$("#progress-bar").style.width=`${current/game.length*100}%`;$("#question-category").textContent=`${q.category.toUpperCase()} · ${q.type==="symbol"?'SYMBOLE':q.type==="written"?'RÉPONSE ÉCRITE':'QCM'}`;$("#question-text").textContent=q.prompt;$("#feedback").hidden=true;$("#next-question").hidden=true;$("#answers").innerHTML="";$("#written-answer").hidden=true;$("#symbol-challenge").hidden=true;if(q.type==="symbol"){$("#symbol-challenge").innerHTML=symbolSVG(q.symbol);$("#symbol-challenge").hidden=false;showWritten()}else if(q.type==="written")showWritten();else{let opts;if(q.type==="qcm")opts=shuffle(q.choices.map((text,i)=>({text,correct:i===q.correct})));else opts=shuffle(q.choices.map(text=>({text,correct:text===q.answer})));$("#answers").innerHTML=opts.map(o=>`<button class="answer" data-correct="${o.correct}">${o.text}</button>`).join('');$$(".answer").forEach(b=>b.onclick=()=>answerChoice(b,q))}}
function showWritten(){$("#written-answer").hidden=false;$("#written-input").value="";$("#written-input").disabled=false;setTimeout(()=>$("#written-input").focus(),50)}
function finishAnswer(correct,q){answered=true;if(correct)score++;$("#quiz-score").textContent=`${score} POINT${score>1?'S':''}`;$("#feedback").innerHTML=`<b>${correct?'Bonne réponse !':'Pas tout à fait.'}</b> ${!correct?`<span class="answer-key">Réponse : ${q.answer||q.choices[q.correct]}.</span> `:""}${q.explanation}`;$("#feedback").hidden=false;$("#next-question").hidden=false;$("#next-question").innerHTML=current===game.length-1?'Voir mon résultat <span>→</span>':'Question suivante <span>→</span>'}
function answerChoice(btn,q){if(answered)return;const correct=btn.dataset.correct==='true';btn.classList.add(correct?'correct':'wrong');if(!correct)$$('.answer').find(b=>b.dataset.correct==='true').classList.add('correct');$$('.answer').forEach(b=>b.disabled=true);finishAnswer(correct,q)}
function answerWritten(e){e.preventDefault();if(answered)return;const q=game[current],value=clean($("#written-input").value);if(!value)return;const accepted=[q.answer,...(q.accepted||[]),...(aliases[q.answer?.toLowerCase()]||[])].filter(Boolean).map(clean);const correct=accepted.some(a=>value===a);$("#written-input").disabled=true;finishAnswer(correct,q)}
function next(){current++;if(current<game.length)showQuestion();else finish()}
function finish(){const previous=Number(localStorage.getItem('plomberieBest')||0);if(score>previous)localStorage.setItem('plomberieBest',score);$("#quiz-game").hidden=true;const pct=Math.round(score/game.length*100);$("#quiz-results").innerHTML=`<span class="kicker">QUIZ TERMINÉ</span><div class="result-score">${score}/${game.length}</div><h3>${pct>=80?'Excellent travail !':pct>=50?'Bonne progression !':'Continuez à réviser !'}</h3><p>${pct}% de bonnes réponses sur une série de ${game.length} questions.</p><button class="btn primary wide" id="restart">Rejouer avec un nouvel ordre ↻</button><button class="btn wide" id="back-quiz">Changer les réglages</button>`;$("#quiz-results").hidden=false;$("#restart").onclick=startQuiz;$("#back-quiz").onclick=()=>{$("#quiz-results").hidden=true;$("#quiz-placeholder").hidden=false;updateBest()}}
$("#start-quiz").onclick=startQuiz;$("#next-question").onclick=next;$("#written-answer").onsubmit=answerWritten;$("#question-total").textContent=`${questionBank.length} questions disponibles`;updateBest();

$$('[data-go]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.go).scrollIntoView({behavior:'smooth'}));
$(".menu-button").onclick=()=>{const h=$(".site-header");h.classList.toggle('open');$(".menu-button").setAttribute('aria-expanded',h.classList.contains('open'))};
$$('.nav-link').forEach(a=>a.onclick=()=>$(".site-header").classList.remove('open'));
const sections=$$('main>section');new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('.nav-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{threshold:.3}).observe(sections[0]);sections.slice(1).forEach(s=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)$$('.nav-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{threshold:.3}).observe(s));
$("#stat-items").textContent=items.length;renderFilters();renderCards();
